export const queryKeys = {
  customers: ["customers"] as const,
  customer: (id: string) => ["customers", id] as const,
  customer360: (id: string) => ["customers", "360", id] as const,
  orders: ["orders"] as const,
  order: (id: string) => ["orders", id] as const,
  payments: ["payments"] as const,
  plans: ["plans"] as const,
  customerPlans: (idComprador: string) => ["plans", "customer", idComprador] as const,
  wallets: ["wallets"] as const,
  bonusWallet: (idComprador: string) => ["wallets", "bonus", idComprador] as const,
  pointsWallet: (idComprador: string) => ["wallets", "points", idComprador] as const,
  network: ["network"] as const,
  analytics: ["analytics"] as const,
  auditLogs: ["audit-logs"] as const,
  audit: {
    logs: (limit: number) => ["audit-logs", limit] as const,
  } as const,
  shipments: ["shipments"] as const,
  alerts: ["alerts"] as const,
  commissions: ["commissions"] as const,
  insights: ["insights"] as const,
  office: {
    dashboard: ["office", "dashboard"] as const,
    finance: ["office", "finance"] as const,
  } as const,
  products: ["products"] as const,
  productDetail: (id: string) => ["products", id] as const,
  paymentAnalytics: ["payment-analytics"] as const,
  walletData: (idComprador: string) => ["wallet-data", idComprador] as const,
  paymentHistory: (idComprador: string) => ["payment-history-list", idComprador] as const,
} as const;
