/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SejaDistribuidorRouteImport } from './routes/seja-distribuidor'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as MinhaContaRouteImport } from './routes/minha-conta'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DoencasRouteImport } from './routes/doencas'
import { Route as DistributorRouteImport } from './routes/distributor'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as BuscaProdutosRouteImport } from './routes/busca-produtos'
import { Route as AtivacaoRouteImport } from './routes/ativacao'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DistributorIndexRouteImport } from './routes/distributor/index'
import { Route as SejaDistribuidorSlugRouteImport } from './routes/seja-distribuidor.$slug'
import { Route as ProdutoIdRouteImport } from './routes/produto.$id'
import { Route as LojaSlugRouteImport } from './routes/loja.$slug'
import { Route as DoencasSlugRouteImport } from './routes/doencas.$slug'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as DistributorVerificationRouteImport } from './routes/distributor/verification'
import { Route as DistributorStoreRouteImport } from './routes/distributor/store'
import { Route as DistributorReportsRouteImport } from './routes/distributor/reports'
import { Route as DistributorProfileRouteImport } from './routes/distributor/profile'
import { Route as DistributorPlanRouteImport } from './routes/distributor/plan'
import { Route as DistributorOrdersRouteImport } from './routes/distributor/orders'
import { Route as DistributorNetworkRouteImport } from './routes/distributor/network'
import { Route as DistributorFinanceRouteImport } from './routes/distributor/finance'
import { Route as DistributorDownloadsRouteImport } from './routes/distributor/downloads'
import { Route as DistributorCopilotRouteImport } from './routes/distributor/copilot'
import { Route as BuscaProdutosSlugRouteImport } from './routes/busca-produtos.$slug'
import { Route as AdminWalletsRouteImport } from './routes/admin/wallets'
import { Route as AdminSystemRouteImport } from './routes/admin/system'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminPlansRouteImport } from './routes/admin/plans'
import { Route as AdminNetworkRouteImport } from './routes/admin/network'
import { Route as AdminMarketingRouteImport } from './routes/admin/marketing'
import { Route as AdminInsightsRouteImport } from './routes/admin/insights'
import { Route as AdminGenealogyRouteImport } from './routes/admin/genealogy'
import { Route as AdminCopilotRouteImport } from './routes/admin/copilot'
import { Route as AdminCommissionsRouteImport } from './routes/admin/commissions'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminAlertsRouteImport } from './routes/admin/alerts'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders/index'
import { Route as AdminIndustrialIndexRouteImport } from './routes/admin/industrial/index'
import { Route as AdminDistributorsIndexRouteImport } from './routes/admin/distributors/index'
import { Route as AdminCustomersIndexRouteImport } from './routes/admin/customers/index'
import { Route as AuthInviteTokenRouteImport } from './routes/auth.invite.$token'
import { Route as AdminIndustrialProcessesRouteImport } from './routes/admin/industrial/processes'
import { Route as AdminIndustrialMaterialsRouteImport } from './routes/admin/industrial/materials'
import { Route as AdminIndustrialMachinesRouteImport } from './routes/admin/industrial/machines'
import { Route as AdminDistributorsIdRouteImport } from './routes/admin/distributors/$id'
import { Route as AdminCustomersIdRouteImport } from './routes/admin/customers/$id'

const SejaDistribuidorRoute = SejaDistribuidorRouteImport.update({
  id: '/seja-distribuidor',
  path: '/seja-distribuidor',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaRoute = MinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DoencasRoute = DoencasRouteImport.update({
  id: '/doencas',
  path: '/doencas',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributorRoute = DistributorRouteImport.update({
  id: '/distributor',
  path: '/distributor',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaProdutosRoute = BuscaProdutosRouteImport.update({
  id: '/busca-produtos',
  path: '/busca-produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const AtivacaoRoute = AtivacaoRouteImport.update({
  id: '/ativacao',
  path: '/ativacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributorIndexRoute = DistributorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DistributorRoute,
} as any)
const SejaDistribuidorSlugRoute = SejaDistribuidorSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SejaDistribuidorRoute,
} as any)
const ProdutoIdRoute = ProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaSlugRoute = LojaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LojaRoute,
} as any)
const DoencasSlugRoute = DoencasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DoencasRoute,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributorVerificationRoute = DistributorVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => DistributorRoute,
} as any)
const DistributorStoreRoute = DistributorStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => DistributorRoute,
} as any)
const DistributorReportsRoute = DistributorReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DistributorRoute,
} as any)
const DistributorProfileRoute = DistributorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DistributorRoute,
} as any)
const DistributorPlanRoute = DistributorPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => DistributorRoute,
} as any)
const DistributorOrdersRoute = DistributorOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DistributorRoute,
} as any)
const DistributorNetworkRoute = DistributorNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => DistributorRoute,
} as any)
const DistributorFinanceRoute = DistributorFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => DistributorRoute,
} as any)
const DistributorDownloadsRoute = DistributorDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => DistributorRoute,
} as any)
const DistributorCopilotRoute = DistributorCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => DistributorRoute,
} as any)
const BuscaProdutosSlugRoute = BuscaProdutosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BuscaProdutosRoute,
} as any)
const AdminWalletsRoute = AdminWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNetworkRoute = AdminNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingRoute = AdminMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInsightsRoute = AdminInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGenealogyRoute = AdminGenealogyRouteImport.update({
  id: '/genealogy',
  path: '/genealogy',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCopilotRoute = AdminCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommissionsRoute = AdminCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlertsRoute = AdminAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIndustrialIndexRoute = AdminIndustrialIndexRouteImport.update({
  id: '/industrial/',
  path: '/industrial/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDistributorsIndexRoute = AdminDistributorsIndexRouteImport.update({
  id: '/distributors/',
  path: '/distributors/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AdminRoute,
} as any)
const AuthInviteTokenRoute = AuthInviteTokenRouteImport.update({
  id: '/auth/invite/$token',
  path: '/auth/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndustrialProcessesRoute =
  AdminIndustrialProcessesRouteImport.update({
    id: '/industrial/processes',
    path: '/industrial/processes',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminIndustrialMaterialsRoute =
  AdminIndustrialMaterialsRouteImport.update({
    id: '/industrial/materials',
    path: '/industrial/materials',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminIndustrialMachinesRoute = AdminIndustrialMachinesRouteImport.update({
  id: '/industrial/machines',
  path: '/industrial/machines',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDistributorsIdRoute = AdminDistributorsIdRouteImport.update({
  id: '/distributors/$id',
  path: '/distributors/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersIdRoute = AdminCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRouteWithChildren
  '/ativacao': typeof AtivacaoRoute
  '/busca-produtos': typeof BuscaProdutosRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/checkout': typeof CheckoutRoute
  '/distributor': typeof DistributorRouteWithChildren
  '/doencas': typeof DoencasRouteWithChildren
  '/login': typeof LoginRoute
  '/loja': typeof LojaRouteWithChildren
  '/minha-conta': typeof MinhaContaRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/seja-distribuidor': typeof SejaDistribuidorRouteWithChildren
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/copilot': typeof AdminCopilotRoute
  '/admin/genealogy': typeof AdminGenealogyRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/network': typeof AdminNetworkRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/busca-produtos/$slug': typeof BuscaProdutosSlugRoute
  '/distributor/copilot': typeof DistributorCopilotRoute
  '/distributor/downloads': typeof DistributorDownloadsRoute
  '/distributor/finance': typeof DistributorFinanceRoute
  '/distributor/network': typeof DistributorNetworkRoute
  '/distributor/orders': typeof DistributorOrdersRoute
  '/distributor/plan': typeof DistributorPlanRoute
  '/distributor/profile': typeof DistributorProfileRoute
  '/distributor/reports': typeof DistributorReportsRoute
  '/distributor/store': typeof DistributorStoreRoute
  '/distributor/verification': typeof DistributorVerificationRoute
  '/docs/$': typeof DocsSplatRoute
  '/doencas/$slug': typeof DoencasSlugRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/seja-distribuidor/$slug': typeof SejaDistribuidorSlugRoute
  '/distributor/': typeof DistributorIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/distributors/$id': typeof AdminDistributorsIdRoute
  '/admin/industrial/machines': typeof AdminIndustrialMachinesRoute
  '/admin/industrial/materials': typeof AdminIndustrialMaterialsRoute
  '/admin/industrial/processes': typeof AdminIndustrialProcessesRoute
  '/auth/invite/$token': typeof AuthInviteTokenRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/distributors/': typeof AdminDistributorsIndexRoute
  '/admin/industrial/': typeof AdminIndustrialIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRouteWithChildren
  '/ativacao': typeof AtivacaoRoute
  '/busca-produtos': typeof BuscaProdutosRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/checkout': typeof CheckoutRoute
  '/doencas': typeof DoencasRouteWithChildren
  '/login': typeof LoginRoute
  '/loja': typeof LojaRouteWithChildren
  '/minha-conta': typeof MinhaContaRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/seja-distribuidor': typeof SejaDistribuidorRouteWithChildren
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/copilot': typeof AdminCopilotRoute
  '/admin/genealogy': typeof AdminGenealogyRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/network': typeof AdminNetworkRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/busca-produtos/$slug': typeof BuscaProdutosSlugRoute
  '/distributor/copilot': typeof DistributorCopilotRoute
  '/distributor/downloads': typeof DistributorDownloadsRoute
  '/distributor/finance': typeof DistributorFinanceRoute
  '/distributor/network': typeof DistributorNetworkRoute
  '/distributor/orders': typeof DistributorOrdersRoute
  '/distributor/plan': typeof DistributorPlanRoute
  '/distributor/profile': typeof DistributorProfileRoute
  '/distributor/reports': typeof DistributorReportsRoute
  '/distributor/store': typeof DistributorStoreRoute
  '/distributor/verification': typeof DistributorVerificationRoute
  '/docs/$': typeof DocsSplatRoute
  '/doencas/$slug': typeof DoencasSlugRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/seja-distribuidor/$slug': typeof SejaDistribuidorSlugRoute
  '/distributor': typeof DistributorIndexRoute
  '/docs': typeof DocsIndexRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/distributors/$id': typeof AdminDistributorsIdRoute
  '/admin/industrial/machines': typeof AdminIndustrialMachinesRoute
  '/admin/industrial/materials': typeof AdminIndustrialMaterialsRoute
  '/admin/industrial/processes': typeof AdminIndustrialProcessesRoute
  '/auth/invite/$token': typeof AuthInviteTokenRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
  '/admin/distributors': typeof AdminDistributorsIndexRoute
  '/admin/industrial': typeof AdminIndustrialIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRouteWithChildren
  '/ativacao': typeof AtivacaoRoute
  '/busca-produtos': typeof BuscaProdutosRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/checkout': typeof CheckoutRoute
  '/distributor': typeof DistributorRouteWithChildren
  '/doencas': typeof DoencasRouteWithChildren
  '/login': typeof LoginRoute
  '/loja': typeof LojaRouteWithChildren
  '/minha-conta': typeof MinhaContaRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/seja-distribuidor': typeof SejaDistribuidorRouteWithChildren
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/copilot': typeof AdminCopilotRoute
  '/admin/genealogy': typeof AdminGenealogyRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/network': typeof AdminNetworkRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/busca-produtos/$slug': typeof BuscaProdutosSlugRoute
  '/distributor/copilot': typeof DistributorCopilotRoute
  '/distributor/downloads': typeof DistributorDownloadsRoute
  '/distributor/finance': typeof DistributorFinanceRoute
  '/distributor/network': typeof DistributorNetworkRoute
  '/distributor/orders': typeof DistributorOrdersRoute
  '/distributor/plan': typeof DistributorPlanRoute
  '/distributor/profile': typeof DistributorProfileRoute
  '/distributor/reports': typeof DistributorReportsRoute
  '/distributor/store': typeof DistributorStoreRoute
  '/distributor/verification': typeof DistributorVerificationRoute
  '/docs/$': typeof DocsSplatRoute
  '/doencas/$slug': typeof DoencasSlugRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/seja-distribuidor/$slug': typeof SejaDistribuidorSlugRoute
  '/distributor/': typeof DistributorIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/distributors/$id': typeof AdminDistributorsIdRoute
  '/admin/industrial/machines': typeof AdminIndustrialMachinesRoute
  '/admin/industrial/materials': typeof AdminIndustrialMaterialsRoute
  '/admin/industrial/processes': typeof AdminIndustrialProcessesRoute
  '/auth/invite/$token': typeof AuthInviteTokenRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/distributors/': typeof AdminDistributorsIndexRoute
  '/admin/industrial/': typeof AdminIndustrialIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/admin'
    | '/ativacao'
    | '/busca-produtos'
    | '/cadastro'
    | '/checkout'
    | '/distributor'
    | '/doencas'
    | '/login'
    | '/loja'
    | '/minha-conta'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/seja-distribuidor'
    | '/admin/alerts'
    | '/admin/analytics'
    | '/admin/commissions'
    | '/admin/copilot'
    | '/admin/genealogy'
    | '/admin/insights'
    | '/admin/marketing'
    | '/admin/network'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/system'
    | '/admin/wallets'
    | '/busca-produtos/$slug'
    | '/distributor/copilot'
    | '/distributor/downloads'
    | '/distributor/finance'
    | '/distributor/network'
    | '/distributor/orders'
    | '/distributor/plan'
    | '/distributor/profile'
    | '/distributor/reports'
    | '/distributor/store'
    | '/distributor/verification'
    | '/docs/$'
    | '/doencas/$slug'
    | '/loja/$slug'
    | '/produto/$id'
    | '/seja-distribuidor/$slug'
    | '/distributor/'
    | '/docs/'
    | '/admin/customers/$id'
    | '/admin/distributors/$id'
    | '/admin/industrial/machines'
    | '/admin/industrial/materials'
    | '/admin/industrial/processes'
    | '/auth/invite/$token'
    | '/admin/customers/'
    | '/admin/distributors/'
    | '/admin/industrial/'
    | '/admin/orders/'
    | '/admin/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/admin'
    | '/ativacao'
    | '/busca-produtos'
    | '/cadastro'
    | '/checkout'
    | '/doencas'
    | '/login'
    | '/loja'
    | '/minha-conta'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/seja-distribuidor'
    | '/admin/alerts'
    | '/admin/analytics'
    | '/admin/commissions'
    | '/admin/copilot'
    | '/admin/genealogy'
    | '/admin/insights'
    | '/admin/marketing'
    | '/admin/network'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/system'
    | '/admin/wallets'
    | '/busca-produtos/$slug'
    | '/distributor/copilot'
    | '/distributor/downloads'
    | '/distributor/finance'
    | '/distributor/network'
    | '/distributor/orders'
    | '/distributor/plan'
    | '/distributor/profile'
    | '/distributor/reports'
    | '/distributor/store'
    | '/distributor/verification'
    | '/docs/$'
    | '/doencas/$slug'
    | '/loja/$slug'
    | '/produto/$id'
    | '/seja-distribuidor/$slug'
    | '/distributor'
    | '/docs'
    | '/admin/customers/$id'
    | '/admin/distributors/$id'
    | '/admin/industrial/machines'
    | '/admin/industrial/materials'
    | '/admin/industrial/processes'
    | '/auth/invite/$token'
    | '/admin/customers'
    | '/admin/distributors'
    | '/admin/industrial'
    | '/admin/orders'
    | '/admin/products'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/admin'
    | '/ativacao'
    | '/busca-produtos'
    | '/cadastro'
    | '/checkout'
    | '/distributor'
    | '/doencas'
    | '/login'
    | '/loja'
    | '/minha-conta'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/seja-distribuidor'
    | '/admin/alerts'
    | '/admin/analytics'
    | '/admin/commissions'
    | '/admin/copilot'
    | '/admin/genealogy'
    | '/admin/insights'
    | '/admin/marketing'
    | '/admin/network'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/system'
    | '/admin/wallets'
    | '/busca-produtos/$slug'
    | '/distributor/copilot'
    | '/distributor/downloads'
    | '/distributor/finance'
    | '/distributor/network'
    | '/distributor/orders'
    | '/distributor/plan'
    | '/distributor/profile'
    | '/distributor/reports'
    | '/distributor/store'
    | '/distributor/verification'
    | '/docs/$'
    | '/doencas/$slug'
    | '/loja/$slug'
    | '/produto/$id'
    | '/seja-distribuidor/$slug'
    | '/distributor/'
    | '/docs/'
    | '/admin/customers/$id'
    | '/admin/distributors/$id'
    | '/admin/industrial/machines'
    | '/admin/industrial/materials'
    | '/admin/industrial/processes'
    | '/auth/invite/$token'
    | '/admin/customers/'
    | '/admin/distributors/'
    | '/admin/industrial/'
    | '/admin/orders/'
    | '/admin/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AdminRoute: typeof AdminRouteWithChildren
  AtivacaoRoute: typeof AtivacaoRoute
  BuscaProdutosRoute: typeof BuscaProdutosRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  CheckoutRoute: typeof CheckoutRoute
  DistributorRoute: typeof DistributorRouteWithChildren
  DoencasRoute: typeof DoencasRouteWithChildren
  LoginRoute: typeof LoginRoute
  LojaRoute: typeof LojaRouteWithChildren
  MinhaContaRoute: typeof MinhaContaRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  SejaDistribuidorRoute: typeof SejaDistribuidorRouteWithChildren
  DocsSplatRoute: typeof DocsSplatRoute
  ProdutoIdRoute: typeof ProdutoIdRoute
  DocsIndexRoute: typeof DocsIndexRoute
  AuthInviteTokenRoute: typeof AuthInviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seja-distribuidor': {
      id: '/seja-distribuidor'
      path: '/seja-distribuidor'
      fullPath: '/seja-distribuidor'
      preLoaderRoute: typeof SejaDistribuidorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta': {
      id: '/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof MinhaContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doencas': {
      id: '/doencas'
      path: '/doencas'
      fullPath: '/doencas'
      preLoaderRoute: typeof DoencasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distributor': {
      id: '/distributor'
      path: '/distributor'
      fullPath: '/distributor'
      preLoaderRoute: typeof DistributorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca-produtos': {
      id: '/busca-produtos'
      path: '/busca-produtos'
      fullPath: '/busca-produtos'
      preLoaderRoute: typeof BuscaProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ativacao': {
      id: '/ativacao'
      path: '/ativacao'
      fullPath: '/ativacao'
      preLoaderRoute: typeof AtivacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distributor/': {
      id: '/distributor/'
      path: '/'
      fullPath: '/distributor/'
      preLoaderRoute: typeof DistributorIndexRouteImport
      parentRoute: typeof DistributorRoute
    }
    '/seja-distribuidor/$slug': {
      id: '/seja-distribuidor/$slug'
      path: '/$slug'
      fullPath: '/seja-distribuidor/$slug'
      preLoaderRoute: typeof SejaDistribuidorSlugRouteImport
      parentRoute: typeof SejaDistribuidorRoute
    }
    '/produto/$id': {
      id: '/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof ProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/$slug': {
      id: '/loja/$slug'
      path: '/$slug'
      fullPath: '/loja/$slug'
      preLoaderRoute: typeof LojaSlugRouteImport
      parentRoute: typeof LojaRoute
    }
    '/doencas/$slug': {
      id: '/doencas/$slug'
      path: '/$slug'
      fullPath: '/doencas/$slug'
      preLoaderRoute: typeof DoencasSlugRouteImport
      parentRoute: typeof DoencasRoute
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distributor/verification': {
      id: '/distributor/verification'
      path: '/verification'
      fullPath: '/distributor/verification'
      preLoaderRoute: typeof DistributorVerificationRouteImport
      parentRoute: typeof DistributorRoute
    }
    '/distributor/store': {
      id: '/distributor/store'
      path: '/store'
      fullPath: '/distributor/store'
      preLoaderRoute: typeof DistributorStoreRouteImport
      parentRoute: typeof DistributorRoute
    }
    '/distributor/reports': {
      id: '/distributor/reports'
      path: '/reports'
      fullPath: '/distributor/reports'
      preLoaderRoute: typeof DistributorReportsRouteImport
      parentRoute: typeof DistributorRoute
    }
    '/distributor/profile': {
      id: '/distributor/profile'
      path: '/profile'
      fullPath: '/distributor/profile'
      preLoaderRoute: typeof DistributorProfileRouteImport
      parentRoute: typeof DistributorRoute
    }
    '/distributor/plan': {
      id: '/distributor/plan'
      path: '/plan'
      fullPath: '/distributor/plan'
      preLoaderRoute: typeof DistributorPlanRouteImport
      parentRoute: typeof DistributorRoute
    }
    '/distributor/orders': {
      id: '/distributor/orders'
      path: '/orders'
      fullPath: '/distributor/orders'
      preLoaderRoute: typeof DistributorOrdersRouteImport
      parentRoute: typeof DistributorRoute
    }
    '/distributor/network': {
      id: '/distributor/network'
      path: '/network'
      fullPath: '/distributor/network'
      preLoaderRoute: typeof DistributorNetworkRouteImport
      parentRoute: typeof DistributorRoute
    }
    '/distributor/finance': {
      id: '/distributor/finance'
      path: '/finance'
      fullPath: '/distributor/finance'
      preLoaderRoute: typeof DistributorFinanceRouteImport
      parentRoute: typeof DistributorRoute
    }
    '/distributor/downloads': {
      id: '/distributor/downloads'
      path: '/downloads'
      fullPath: '/distributor/downloads'
      preLoaderRoute: typeof DistributorDownloadsRouteImport
      parentRoute: typeof DistributorRoute
    }
    '/distributor/copilot': {
      id: '/distributor/copilot'
      path: '/copilot'
      fullPath: '/distributor/copilot'
      preLoaderRoute: typeof DistributorCopilotRouteImport
      parentRoute: typeof DistributorRoute
    }
    '/busca-produtos/$slug': {
      id: '/busca-produtos/$slug'
      path: '/$slug'
      fullPath: '/busca-produtos/$slug'
      preLoaderRoute: typeof BuscaProdutosSlugRouteImport
      parentRoute: typeof BuscaProdutosRoute
    }
    '/admin/wallets': {
      id: '/admin/wallets'
      path: '/wallets'
      fullPath: '/admin/wallets'
      preLoaderRoute: typeof AdminWalletsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/network': {
      id: '/admin/network'
      path: '/network'
      fullPath: '/admin/network'
      preLoaderRoute: typeof AdminNetworkRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing': {
      id: '/admin/marketing'
      path: '/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AdminMarketingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/insights': {
      id: '/admin/insights'
      path: '/insights'
      fullPath: '/admin/insights'
      preLoaderRoute: typeof AdminInsightsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/genealogy': {
      id: '/admin/genealogy'
      path: '/genealogy'
      fullPath: '/admin/genealogy'
      preLoaderRoute: typeof AdminGenealogyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/copilot': {
      id: '/admin/copilot'
      path: '/copilot'
      fullPath: '/admin/copilot'
      preLoaderRoute: typeof AdminCopilotRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commissions': {
      id: '/admin/commissions'
      path: '/commissions'
      fullPath: '/admin/commissions'
      preLoaderRoute: typeof AdminCommissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alerts': {
      id: '/admin/alerts'
      path: '/alerts'
      fullPath: '/admin/alerts'
      preLoaderRoute: typeof AdminAlertsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/industrial/': {
      id: '/admin/industrial/'
      path: '/industrial'
      fullPath: '/admin/industrial/'
      preLoaderRoute: typeof AdminIndustrialIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/distributors/': {
      id: '/admin/distributors/'
      path: '/distributors'
      fullPath: '/admin/distributors/'
      preLoaderRoute: typeof AdminDistributorsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/': {
      id: '/admin/customers/'
      path: '/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/invite/$token': {
      id: '/auth/invite/$token'
      path: '/auth/invite/$token'
      fullPath: '/auth/invite/$token'
      preLoaderRoute: typeof AuthInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/industrial/processes': {
      id: '/admin/industrial/processes'
      path: '/industrial/processes'
      fullPath: '/admin/industrial/processes'
      preLoaderRoute: typeof AdminIndustrialProcessesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/industrial/materials': {
      id: '/admin/industrial/materials'
      path: '/industrial/materials'
      fullPath: '/admin/industrial/materials'
      preLoaderRoute: typeof AdminIndustrialMaterialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/industrial/machines': {
      id: '/admin/industrial/machines'
      path: '/industrial/machines'
      fullPath: '/admin/industrial/machines'
      preLoaderRoute: typeof AdminIndustrialMachinesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/distributors/$id': {
      id: '/admin/distributors/$id'
      path: '/distributors/$id'
      fullPath: '/admin/distributors/$id'
      preLoaderRoute: typeof AdminDistributorsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/$id': {
      id: '/admin/customers/$id'
      path: '/customers/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AdminCustomersIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAlertsRoute: typeof AdminAlertsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCommissionsRoute: typeof AdminCommissionsRoute
  AdminCopilotRoute: typeof AdminCopilotRoute
  AdminGenealogyRoute: typeof AdminGenealogyRoute
  AdminInsightsRoute: typeof AdminInsightsRoute
  AdminMarketingRoute: typeof AdminMarketingRoute
  AdminNetworkRoute: typeof AdminNetworkRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminWalletsRoute: typeof AdminWalletsRoute
  AdminCustomersIdRoute: typeof AdminCustomersIdRoute
  AdminDistributorsIdRoute: typeof AdminDistributorsIdRoute
  AdminIndustrialMachinesRoute: typeof AdminIndustrialMachinesRoute
  AdminIndustrialMaterialsRoute: typeof AdminIndustrialMaterialsRoute
  AdminIndustrialProcessesRoute: typeof AdminIndustrialProcessesRoute
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
  AdminDistributorsIndexRoute: typeof AdminDistributorsIndexRoute
  AdminIndustrialIndexRoute: typeof AdminIndustrialIndexRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAlertsRoute: AdminAlertsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCommissionsRoute: AdminCommissionsRoute,
  AdminCopilotRoute: AdminCopilotRoute,
  AdminGenealogyRoute: AdminGenealogyRoute,
  AdminInsightsRoute: AdminInsightsRoute,
  AdminMarketingRoute: AdminMarketingRoute,
  AdminNetworkRoute: AdminNetworkRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminWalletsRoute: AdminWalletsRoute,
  AdminCustomersIdRoute: AdminCustomersIdRoute,
  AdminDistributorsIdRoute: AdminDistributorsIdRoute,
  AdminIndustrialMachinesRoute: AdminIndustrialMachinesRoute,
  AdminIndustrialMaterialsRoute: AdminIndustrialMaterialsRoute,
  AdminIndustrialProcessesRoute: AdminIndustrialProcessesRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
  AdminDistributorsIndexRoute: AdminDistributorsIndexRoute,
  AdminIndustrialIndexRoute: AdminIndustrialIndexRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BuscaProdutosRouteChildren {
  BuscaProdutosSlugRoute: typeof BuscaProdutosSlugRoute
}

const BuscaProdutosRouteChildren: BuscaProdutosRouteChildren = {
  BuscaProdutosSlugRoute: BuscaProdutosSlugRoute,
}

const BuscaProdutosRouteWithChildren = BuscaProdutosRoute._addFileChildren(
  BuscaProdutosRouteChildren,
)

interface DistributorRouteChildren {
  DistributorCopilotRoute: typeof DistributorCopilotRoute
  DistributorDownloadsRoute: typeof DistributorDownloadsRoute
  DistributorFinanceRoute: typeof DistributorFinanceRoute
  DistributorNetworkRoute: typeof DistributorNetworkRoute
  DistributorOrdersRoute: typeof DistributorOrdersRoute
  DistributorPlanRoute: typeof DistributorPlanRoute
  DistributorProfileRoute: typeof DistributorProfileRoute
  DistributorReportsRoute: typeof DistributorReportsRoute
  DistributorStoreRoute: typeof DistributorStoreRoute
  DistributorVerificationRoute: typeof DistributorVerificationRoute
  DistributorIndexRoute: typeof DistributorIndexRoute
}

const DistributorRouteChildren: DistributorRouteChildren = {
  DistributorCopilotRoute: DistributorCopilotRoute,
  DistributorDownloadsRoute: DistributorDownloadsRoute,
  DistributorFinanceRoute: DistributorFinanceRoute,
  DistributorNetworkRoute: DistributorNetworkRoute,
  DistributorOrdersRoute: DistributorOrdersRoute,
  DistributorPlanRoute: DistributorPlanRoute,
  DistributorProfileRoute: DistributorProfileRoute,
  DistributorReportsRoute: DistributorReportsRoute,
  DistributorStoreRoute: DistributorStoreRoute,
  DistributorVerificationRoute: DistributorVerificationRoute,
  DistributorIndexRoute: DistributorIndexRoute,
}

const DistributorRouteWithChildren = DistributorRoute._addFileChildren(
  DistributorRouteChildren,
)

interface DoencasRouteChildren {
  DoencasSlugRoute: typeof DoencasSlugRoute
}

const DoencasRouteChildren: DoencasRouteChildren = {
  DoencasSlugRoute: DoencasSlugRoute,
}

const DoencasRouteWithChildren =
  DoencasRoute._addFileChildren(DoencasRouteChildren)

interface LojaRouteChildren {
  LojaSlugRoute: typeof LojaSlugRoute
}

const LojaRouteChildren: LojaRouteChildren = {
  LojaSlugRoute: LojaSlugRoute,
}

const LojaRouteWithChildren = LojaRoute._addFileChildren(LojaRouteChildren)

interface SejaDistribuidorRouteChildren {
  SejaDistribuidorSlugRoute: typeof SejaDistribuidorSlugRoute
}

const SejaDistribuidorRouteChildren: SejaDistribuidorRouteChildren = {
  SejaDistribuidorSlugRoute: SejaDistribuidorSlugRoute,
}

const SejaDistribuidorRouteWithChildren =
  SejaDistribuidorRoute._addFileChildren(SejaDistribuidorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AdminRoute: AdminRouteWithChildren,
  AtivacaoRoute: AtivacaoRoute,
  BuscaProdutosRoute: BuscaProdutosRouteWithChildren,
  CadastroRoute: CadastroRoute,
  CheckoutRoute: CheckoutRoute,
  DistributorRoute: DistributorRouteWithChildren,
  DoencasRoute: DoencasRouteWithChildren,
  LoginRoute: LoginRoute,
  LojaRoute: LojaRouteWithChildren,
  MinhaContaRoute: MinhaContaRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  SejaDistribuidorRoute: SejaDistribuidorRouteWithChildren,
  DocsSplatRoute: DocsSplatRoute,
  ProdutoIdRoute: ProdutoIdRoute,
  DocsIndexRoute: DocsIndexRoute,
  AuthInviteTokenRoute: AuthInviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
